### PR TITLE
"fewer", not "less"

### PR DESCRIPTION
**Pull request by rv3r**
I swear English is my first language.

### CODE REVIEW

**Review by Ghoulboy78 — APPROVED** [review]
lol

**Comment by altrisi** [comment]
Not English, would've used less too, is there a difference between them? In my head they mean the same.

**Comment by Ghoulboy78** [comment]
Technically 'less' cannot be used as a comparative adjective, which is the context of the sentence. The sentence that rv3r is changing is referring to the side of the portal which has fewer solid blocks, while using 'less solid blocks' could imply that those blocks are less solid, instead of there being a smaller number of solid blocks.
In practice, the only people to care are English teachers, because as you mentioned, it makes sense to anyone who is reading the entire sentence.

But viva el pedanticism!

**Comment by rv3r** [comment]
It's my script and the language is inconsistent, which is mostly why I fixed it.

**Review by altrisi — APPROVED** [review]

**Pull request merged**
