### PR TITLE
Adding Waypoints app

### PR DESCRIPTION
**Pull request by Firigion**
This app adds server-side waypoints for communal servers, where farms and POIs are of common interest to all players. Players can teleport to waypoints, if allowed (persmissions are highly customizable), or have a line render point to the selected waypoint.

The main functionality of the app can be seen here: https://youtu.be/OF_hY1sTRYY
The direction hinting is here: https://youtu.be/0N2qVahMD7s

### CODE REVIEW

**Review by altrisi — APPROVED** [review]
Noooo, why I'm so lazy. I gotta finish my own soon :(, it's been almost a year since I started it.

Looks good though, didn't really test it but I trust it'll work, plus I saw the showcases.

May do a more thorough review later to find things to improve (and maybe to steal some ideas too okno), though it looks quite good already.

**Comment by altrisi** [comment]
I actually stopped developing mine at direction hinting, lol. I'll have to see how it's done here, although I kinda already have a small idea in how to do it.

**Review by Ghoulboy78 — APPROVED** [review]
Already saw the role in boyoenn's repo

**Comment by CallMeChin** [comment]
Is it possible to make it so that it automatically converts coordinate between worlds?
In theory it shouldn't be hard, but then i don't have any knowledge with java

**Pull request merged**
