### PR TITLE
update to villager POI system

### PR DESCRIPTION
**Pull request by sanketc001**

### CODE REVIEW

**Review by Firigion — APPROVED** [review]
Thanks

**Review by Ghoulboy78 — APPROVED** [review]

**Comment by altrisi** [comment]
Can't really find any reference to emeralds in the script, though.

**Comment by Ghoulboy78** [comment]
OH gosh, yes, you're right mate. Whoops.

**Comment by altrisi** [comment]
Only reference I can find to emeralds seems to be from the `track` command in base Carpet, which seems to do exactly that. At

https://github.com/gnembon/fabric-carpet/blob/3bf3c3116071fa4917f034e01c9ffa999b3edd2a/src/main/java/carpet/mixins/VillagerEntity_aiMixin.java#L122

**Comment by altrisi** [comment]
Hello @sanketc001, thanks for contributing!

I think you confused the `villager_poi.sc` app from this repo with the features of the `/track` command in Carpet, is that possible? If you wanted to contribute documenting that command, you should instead go to the [Commands](https://github.com/gnembon/fabric-carpet/wiki/Commands) page of the Carpet wiki, where the track command is also undocumented.

Thanks!

_If I'm incorrect in something, please reply and I'll reopen this issue._

**Pull request closed without merging**
