### PR TITLE
Update camera.sc compared to Fabric Carpet (alternative to #187)

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**
I made #187 to remove the script, but then @BisUmTo said we should just update it. I will keep both PRs open and you can choose which to merge.

### CODE REVIEW

**Review by altrisi — APPROVED** [review]
~I'd also add the comment to the README of that section to reflect that the latest version is already bundled in Carpet's assets.~ Nvm, just found that section has no readme with a list of apps.

Also currently there is actually a PR touching this app in main Carpet repo (gnembon/fabric-carpet#740), not sure if this should wait, supposing that doesn't take long to be merged.

**Comment by altrisi** [comment]
BTW: The Scarpet app repo is currently ran by maintainers in a 2 approval reviews -> merge basis.

**Comment by DragonEggBedrockBreaking** [comment]
> BTW: The Scarpet app repo is currently ran by maintainers in a 2 approval reviews -> merge basis.

I receive an email when something happens, so I can close the other PR once this is merged.

**Comment by BisUmTo** [comment]
> ~I'd also add the comment to the README of that section to reflect that the latest version is already bundled in Carpet's assets.~ Nvm, just found that section has no readme with a list of apps.
> 
> Also currently there is actually a PR touching this app in main Carpet repo (gnembon/fabric-carpet#740), not sure if this should wait, supposing that doesn't take long to be merged.

I'll leave my approval, so you can merge as soon as the other PR (gnembon/fabric-carpet#740) is merged 😉

**Review by BisUmTo — APPROVED** [review]

**Comment by DragonEggBedrockBreaking** [comment]
> I'll leave my approval, so you can merge as soon as the other PR ([gnembon/fabric-carpet#740](https://github.com/gnembon/fabric-carpet/pull/740)) is merged 😉

I subscribed to the thread on https://github.com/gnembon/fabric-carpet/pull/740 so that I get I can see if/when it is merged.

**Comment by DragonEggBedrockBreaking** [comment]
https://github.com/gnembon/fabric-carpet/pull/740 got merged and I have now updated camera.sc again :-)

**Review by altrisi — APPROVED** [review]

**Comment by altrisi** [comment]
It's ending up being deleted in #343 after a year and a half.

**Comment by Ghoulboy78** [comment]
Because I'm an idiot and didn't read it through properly lol...

**Pull request merged**
