### PR TITLE
Add CommandLeo's Stat App

### PR DESCRIPTION
**Pull request by JacktheDevel0per**
Does CommandLeo Only want it to be in the Mechanists Discord? If so I will Remove Completely, It its technically "Public", but don't want to upset CommandLeo

(Also Added Levels to it to see player Levels)

### CODE REVIEW

**Comment by CommandLeo** [comment]
I'm fine with it being in the appstore 👍
At some point I'm going to rewrite it tho, but when that happens I'll open a new pull request

**Review by CommandLeo — APPROVED** [review]

**Comment by JacktheDevel0per** [comment]
Nice

**Comment by JacktheDevel0per** [comment]
Does gnembon have to actually merge it?

**Review by Ghoulboy78 — APPROVED** [review]
Well no, it takes 2 contributors, and now that I've approved, only one more person needs to approve to get it through.

**Comment by JacktheDevel0per** [comment]
How does someone become a contributor?

**Comment by Ghoulboy78** [comment]
To be completely honest, I haven't a clue.

**Review by CommandLeo — APPROVED** [review]

**Review by MeeniMc — APPROVED** [review]

**Review by Firigion — APPROVED** [review]
woops, forgot about this one

**Comment by JacktheDevel0per** [comment]
So it's ready to be merged what happens now?

**Comment by Ghoulboy78** [comment]
Well, now I merge ig

**Pull request merged**
